name: CI/CD Drug Classification Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-train-eval-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: make install

      - name: Train model
        run: make train

      - name: Evaluate model
        run: make eval

      - name: Update branch with model/results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make update-branch

      - name: Deploy to Hugging Face Spaces
        env:
          HF: ${{ secrets.HF }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make deploy